---
apiVersion: v1
kind: Service
metadata:
  name: sickrage
  labels:
    app: sickrage
spec:
  selector:
    app: sickrage
  ports:
    - port: 8081
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sickrage
  labels:
    app: sickrage
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: sickrage
    spec:
      securityContext:
        fsGroup: 5001
      containers:
        - name: sickrage
          image: "linuxserver/sickrage"
          ports:
            - name: sick-port
              containerPort: 8081
          volumeMounts:
            - name: sickrage-config
              mountPath: /config
            - name: sickrage-downloads
              mountPath: /downloads
          env:
            - name: VERSION
              value: "latest"
            - name: PGID
              value: "5001"
            - name: PUID
              value: "5001"
            - name: TZ
              value: "Europe/Paris"
      volumes:
        - name: sickrage-config
          hostPath:
            path: /srv/configs/sickrage
        - name: sickrage-downloads
          hostPath:
            path: /srv/seedbox
